# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      build_version:
        enabled: true

builders:
  build_version:
    import: "package:build_version/builder.dart"
    builder_factories: ["buildVersion"]
    build_extensions: {"pubspec.yaml": ["lib/src/version.dart"]}
    defaults:
      options:
        output: "lib/src/version.dart"
    build_to: source
    auto_apply: dependents
